import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/components/admin-apnet/AuthProvider";
import { Toaster } from "react-hot-toast"; 
import App from "./App";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <App>{children}</App>
        </AuthProvider>
        <Toaster position="bottom-center" reverseOrder={false} />
      </body>
    </html>
  );
};